version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: repeatpro
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - .:/django
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:14-alpine



