# Generated by Django 4.2.3 on 2023-07-31 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tutors.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Course name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='tutorcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.courses', validators=[tutors.models.validate_courses]),
        ),
        migrations.AlterField(
            model_name='tutoruser',
            name='courses',
            field=models.ManyToManyField(through='tutors.TutorCourse', to='tutors.courses', validators=[tutors.models.validate_courses]),
        ),
        migrations.CreateModel(
            name='TutorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Accept', 'Accept Request'), ('Reject', 'Reject Request'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutors.clientuser')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
