# Generated by Django 4.2.3 on 2023-08-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_alter_courses_name_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accept Request'), ('Rejected', 'Reject Request'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True),
        ),
    ]
