# Generated by Django 4.2.3 on 2023-08-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_tutorrequest_lesson_slot_delete_lessonschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonslot',
            name='tutor',
        ),
    ]
