# Generated by Django 4.2.3 on 2023-08-04 11:59

from django.db import migrations, models
import tutors.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0008_remove_tutorrequest_lesson_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='tutoruser',
            name='activate_post',
            field=models.BooleanField(default=False, verbose_name='Acticate Profile'),
        ),
        migrations.AlterField(
            model_name='tutoruser',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatars/default_avatar.png', null=True, upload_to='media\\avatars/%Y/%m/%d', verbose_name='Profile Avatar'),
        ),
        migrations.AlterField(
            model_name='tutoruser',
            name='bio',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='About Me'),
        ),
        migrations.AlterField(
            model_name='tutoruser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='tutoruser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='tutoruser',
            name='degree',
            field=models.CharField(blank=True, choices=[('st', 'Студент'), ('bch', 'Бакалавр'), ('mg', 'Магистр'), ('phd', 'Кандидат Наук'), ('pf', 'Профессор')], max_length=255, null=True, verbose_name='Academic Degree'),
        ),
        migrations.AlterField(
            model_name='tutoruser',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Education/University'),
        ),
        migrations.AlterField(
            model_name='tutoruser',
            name='experience',
            field=models.IntegerField(blank=True, choices=[(0, 'Менее 1 года'), (1, 'Более 1 года'), (2, 'Более 2 лет'), (3, 'Более 3 лет'), (5, 'Более 5 лет'), (10, 'Более 10 лет')], max_length=20, null=True, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='tutoruser',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='fmedia\\files/%Y/%m/%d', verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='tutoruser',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='tutoruser',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='tutoruser',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Video Link'),
        ),
        migrations.AlterField(
            model_name='tutoruser',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='tutoruser',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone Num'),
        ),
        migrations.AlterField(
            model_name='tutoruser',
            name='salary',
            field=models.IntegerField(blank=True, choices=[(1000, '1000 тнг/час'), (2000, '2000 тнг/час'), (3000, '3000 тнг/час'), (4000, '4000 тнг/час'), (5000, '5000 тнг/час'), (6000, '6000 тнг/час'), (7000, '7000 тнг/час'), (8000, '8000 тнг/час'), (9000, '9000 тнг/час'), (10000, '10000 тнг/час'), (11000, '11000 тнг/час')], max_length=200, null=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='tutoruser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='tutoruser',
            name='yof',
            field=models.IntegerField(blank=True, null=True, validators=[tutors.models.TutorUser.positive_validator], verbose_name='Year of Ending '),
        ),
    ]
