# Generated by Django 4.2.3 on 2023-08-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0010_alter_tutoruser_activate_post_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoruser',
            name='avatar',
            field=models.ImageField(blank=True, default='https://ssl.gstatic.com/images/branding/product/1x/avatar_square_blue_512dp.png', null=True, upload_to='media\\avatars/%Y/%m/%d', verbose_name='Profile Avatar'),
        ),
    ]
