# Generated by Django 4.2.3 on 2023-08-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0011_alter_tutoruser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoruser',
            name='avatar',
            field=models.ImageField(default='tutor_avatars/tutor_avatar_def.png', upload_to='tutor_avatars/', verbose_name='Profile Avatar'),
        ),
    ]
